### PR TITLE
task/input-change-password

### LINKED ISSUE #8: perbaikan logic deteksi validasi email atau username ketika login
current:
- deteksi param "umail" lalu cek apakah ada simbol "@" untuk menentukan pengecekan melalui apa

Goals:
- ambil value param "umail" lalu pengecekan pertama berdasarkan email jikalau tidak ada lanjut ngecek username, jikalau tidak ada berarti invalid

### LINKED ISSUE #10: [BE] Email Template For Forgot Passwords

### LINKED ISSUE #12: [BE] fix input for change password

### PR DESCRIPTION
**Pull request by xamppsul**
- fix input change password account mentor/user
- after success change password then send notif success reset to user/mentor via email.

### CODE REVIEW

**Comment by xamppsul** [comment]
@suhafer ready to testing kak thanks

**Review by suhafer — CHANGES_REQUESTED** [review]
Mintol merge change terakhir dari branch main ya

**Comment by xamppsul** [comment]
> Mintol merge change terakhir dari branch main ya

siap kak @suhafer

**Comment by xamppsul** [comment]
> Mintol merge change terakhir dari branch main ya

sudah yah kak @suhafer

**Review by suhafer — APPROVED** [review]

**Pull request merged**
