### PR TITLE
task/email-template-for-verify-forgotpass

### LINKED ISSUE #10: [BE] Email Template For Forgot Passwords

### PR DESCRIPTION
**Pull request by xamppsul**
- fix layout email template for verify account
- fix layout email template for forgot pass and use username and link of send data to template email forgot password

### CODE REVIEW

**Review by suhafer — CHANGES_REQUESTED** [review]
Mintol merge change terakhir dari branch main ya

**Comment by xamppsul** [comment]
> Mintol merge change terakhir dari branch main ya

sudah kak @suhafer

**Review by suhafer — APPROVED** [review]

**Review by suhafer — CHANGES_REQUESTED** [review]
belum di merge change terakhir dari branch main ternyata

**Comment by suhafer** [comment]
closed karena commit change include in [here](https://github.com/Betalogika/halokak-be-lumen/pull/13)

**Pull request closed without merging**
